// vue-vs-react/vue-app/src/App.vue
<template>
    <header className="App-header">
      <p>Count: {{ count }}</p>
      <button @click="increment">+1</button>
    </header>
</template>

<script>
export default {
  data() {
    return {
      count: 0,
    };
  },
  methods: {
    increment() {
      this.count++;
    },
  },
};
</script>

// vue-vs-react/react-app/src/App.js
import { React, useState } from "react";

function App() {
  const [count, setCount] = useState(0);

  return (
      <header className="App-header">
        <p>Count: {count}</p>
        <button
          onClick={() => {
            setCount(count + 1);
          }}
        >
          +1
        </button>
      </header>
  );
}

export default App;
